services:
  ski-project:
    image: medkrimi1/ski-project
    container_name: ski-project
    ports:
      - "9091:9091"
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/SkiStationDB?createDatabaseIfNotExist=true

